//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendSyncDB.ModeloFriendSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigos
    {
        public int Id { get; set; }
        public Nullable<int> UsuarioId1 { get; set; }
        public Nullable<int> UsuarioId2 { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaAceptacion { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
