//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendSyncDB.ModeloFriendSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicaciones()
        {
            this.Comentarios = new HashSet<Comentarios>();
        }
    
        public int IdPublicacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Contenido { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public byte[] Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        public virtual users users { get; set; }
    }
}
